In [1]:
import numpy as np
import pandas as pd

In [2]:
string_data = pd.Series(['aardvark','b',np.nan,'v'])

In [3]:
string_data

0    aardvark
1           b
2         NaN
3           v
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [14]:
string_data2 = string_data.fillna('e')

In [15]:
string_data

0    e
1    b
2    e
3    v
dtype: object

In [16]:
from numpy import nan as NA

In [17]:
data = pd.Series([1,NA,3.5,NA,7])

In [18]:
DATA

NameError: name 'DATA' is not defined

In [19]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [20]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [21]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [23]:
data = pd.DataFrame([[1,6.5,3],[1,NA,NA],[NA,NA,NA],[NA,6.5,3]])

In [24]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [25]:
cleaned = data.dropna()

In [26]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [28]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [33]:
data[4] = NA

In [34]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [35]:
data.dropna(1,how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [36]:
df = pd.DataFrame(np.random.randn(7,3))

In [37]:
df

0         1         2
0  0.987941  1.018760 -0.316357
1 -0.330748  0.452510 -0.902068
2  0.621237  0.454195 -0.237723
3 -0.703876 -0.053693 -0.023983
4 -0.661918 -1.162799 -0.614553
5 -0.124768  0.116578  0.614954
6  1.305081 -0.106273 -0.645568

In [38]:
df.iloc[:4,1] = NA

In [40]:
df.iloc[:2,2] = NA

In [41]:
df

0         1         2
0  0.987941       NaN       NaN
1 -0.330748       NaN       NaN
2  0.621237       NaN -0.237723
3 -0.703876       NaN -0.023983
4 -0.661918 -1.162799 -0.614553
5 -0.124768  0.116578  0.614954
6  1.305081 -0.106273 -0.645568

In [42]:
df.dropna()

0         1         2
4 -0.661918 -1.162799 -0.614553
5 -0.124768  0.116578  0.614954
6  1.305081 -0.106273 -0.645568

In [46]:
df.dropna(thresh = 2)

0         1         2
2  0.621237       NaN -0.237723
3 -0.703876       NaN -0.023983
4 -0.661918 -1.162799 -0.614553
5 -0.124768  0.116578  0.614954
6  1.305081 -0.106273 -0.645568

In [47]:
df.fillna(0)

0         1         2
0  0.987941  0.000000  0.000000
1 -0.330748  0.000000  0.000000
2  0.621237  0.000000 -0.237723
3 -0.703876  0.000000 -0.023983
4 -0.661918 -1.162799 -0.614553
5 -0.124768  0.116578  0.614954
6  1.305081 -0.106273 -0.645568

In [48]:
df.fillna({1:3.14159,2:6.28})

0         1         2
0  0.987941  3.141590  6.280000
1 -0.330748  3.141590  6.280000
2  0.621237  3.141590 -0.237723
3 -0.703876  3.141590 -0.023983
4 -0.661918 -1.162799 -0.614553
5 -0.124768  0.116578  0.614954
6  1.305081 -0.106273 -0.645568

In [52]:
_ = df.fillna(0,inplace = True)

In [53]:
df

0         1         2
0  0.987941  0.000000  0.000000
1 -0.330748  0.000000  0.000000
2  0.621237  0.000000 -0.237723
3 -0.703876  0.000000 -0.023983
4 -0.661918 -1.162799 -0.614553
5 -0.124768  0.116578  0.614954
6  1.305081 -0.106273 -0.645568

In [54]:
df = pd.DataFrame(np.random.randn(6,3))

In [55]:
df

0         1         2
0  0.413907 -2.244151  0.595928
1  1.382193  0.033694  1.662573
2  0.497488  0.048018 -0.779637
3  0.285817  0.117248  0.517872
4 -0.949388 -0.776042 -0.758364
5  0.078345 -0.396604  0.119468

In [56]:
df.iloc[2:,1] = NA

In [58]:
df.iloc[4:,2] = NA

In [59]:
df

0         1         2
0  0.413907 -2.244151  0.595928
1  1.382193  0.033694  1.662573
2  0.497488       NaN -0.779637
3  0.285817       NaN  0.517872
4 -0.949388       NaN       NaN
5  0.078345       NaN       NaN

In [60]:
df.fillna(method = 'ffill') #ffill向上填充

0         1         2
0  0.413907 -2.244151  0.595928
1  1.382193  0.033694  1.662573
2  0.497488  0.033694 -0.779637
3  0.285817  0.033694  0.517872
4 -0.949388  0.033694  0.517872
5  0.078345  0.033694  0.517872

In [62]:
df.fillna(method = 'ffill', limit = 2) #加入limit = 2 填充两个

0         1         2
0  0.413907 -2.244151  0.595928
1  1.382193  0.033694  1.662573
2  0.497488  0.033694 -0.779637
3  0.285817  0.033694  0.517872
4 -0.949388       NaN  0.517872
5  0.078345       NaN  0.517872

In [63]:
data = pd.Series([1,NA,3.5,NA,7])

In [64]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [67]:
data.fillna(data.mean()).round(2)

0    1.00
1    3.83
2    3.50
3    3.83
4    7.00
dtype: float64

In [68]:
data = pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})

In [69]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [71]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [73]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [75]:
data['av1'] = range(7)

In [76]:
data

k1  k2  av1
0  one   1    0
1  two   1    1
2  one   2    2
3  two   3    3
4  one   3    4
5  two   4    5
6  two   4    6

In [78]:
data.drop_duplicates(['k1'])

k1  k2  av1
0  one   1    0
1  two   1    1

In [80]:
data.drop_duplicates(['k1','k2'],keep = 'last')

k1  k2  av1
0  one   1    0
1  two   1    1
2  one   2    2
3  two   3    3
4  one   3    4
6  two   4    6

In [85]:
data = pd.DataFrame({'food': ['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],
                     'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [86]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [94]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [95]:
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [96]:
lowercased = data['food'].str.lower()

In [97]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [98]:
data ['amimal'] = lowercased.map(meat_to_animal)

In [99]:
data

food  ounces  amimal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [102]:
data['animal2'] = data['food'].map(lambda x:meat_to_animal[x.lower()])

In [103]:
data

food  ounces  amimal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     Pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        Bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

In [104]:
data = pd.Series([1,-999,2,-999,-1000,3])

In [105]:
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [108]:
data.replace([-999,-1000],[np.nan,'wocao'])

0        1
1      NaN
2        2
3      NaN
4    wocao
5        3
dtype: object

In [111]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index = ['Ohio','Colorado','New York'],
                   columns = ['one','two','three','four'])

In [112]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [113]:
transform = lambda x : x[:4].upper()

In [114]:
transform

<function __main__.<lambda>(x)>

In [115]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [116]:
data.index = data.index.map(transform)

In [117]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [120]:
data.rename(index = str.title,columns = str.upper,inplace = True)

In [121]:
data

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [122]:
age = [20,22,25,27,21,23,37,31,61,45,41,32]

In [123]:
age

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [124]:
bins = [18,25,35,60,100]

In [125]:
cats = pd.cut(age,bins)

In [126]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [127]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [128]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [129]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [130]:
group_names = ['youth','youngadult','middleaged','senior']

In [132]:
cats = pd.cut(age,bins,labels = group_names)

In [133]:
cats.value_counts()

youth         5
youngadult    3
middleaged    3
senior        1
dtype: int64

In [134]:
data = np.random.rand(20)

In [135]:
data

array([0.60981313, 0.25907737, 0.97504861, 0.66410594, 0.8985642 ,
       0.20609258, 0.69764467, 0.75569186, 0.12895778, 0.38733011,
       0.01517113, 0.77319993, 0.16452636, 0.75958957, 0.32865263,
       0.11653042, 0.01369893, 0.72278192, 0.18737625, 0.15085085])

In [136]:
pd.cut(data,4,precision=4)

[(0.4944, 0.7347], (0.254, 0.4944], (0.7347, 0.975], (0.4944, 0.7347], (0.7347, 0.975], ..., (0.01274, 0.254], (0.01274, 0.254], (0.4944, 0.7347], (0.01274, 0.254], (0.01274, 0.254]]
Length: 20
Categories (4, interval[float64]): [(0.01274, 0.254] < (0.254, 0.4944] < (0.4944, 0.7347] < (0.7347, 0.975]]

In [137]:
data = np.random.randn(1000)

In [139]:
cats = pd.qcut(data,4)

In [140]:
cats

[(0.0331, 0.692], (-0.672, 0.0331], (-3.207, -0.672], (-0.672, 0.0331], (0.0331, 0.692], ..., (-0.672, 0.0331], (-0.672, 0.0331], (-0.672, 0.0331], (-0.672, 0.0331], (0.692, 3.198]]
Length: 1000
Categories (4, interval[float64]): [(-3.207, -0.672] < (-0.672, 0.0331] < (0.0331, 0.692] < (0.692, 3.198]]

In [141]:
cats.value_counts()

(-3.207, -0.672]    250
(-0.672, 0.0331]    250
(0.0331, 0.692]     250
(0.692, 3.198]      250
dtype: int64

In [143]:
cats2 = pd.qcut(data,[0,0.1,0.5,0.9,1])

In [144]:
cats2.value_counts()

(-3.207, -1.261]    100
(-1.261, 0.0331]    400
(0.0331, 1.332]     400
(1.332, 3.198]      100
dtype: int64

In [145]:
data = pd.DataFrame(np.random.randn(1000,4))

In [146]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.003457    -0.016973    -0.028008     0.011182
std       0.984090     0.996347     0.981218     1.005981
min      -2.729081    -2.946380    -3.004744    -2.822673
25%      -0.662756    -0.701593    -0.701784    -0.676590
50%      -0.009459    -0.046370    -0.034150     0.061440
75%       0.632105     0.673459     0.648194     0.714151
max       3.385960     2.985882     3.026870     2.873912

In [147]:
col = data[2]

In [148]:
col[np.abs(col)>3]

275    3.026870
559   -3.004744
Name: 2, dtype: float64

In [149]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
275  0.568131 -1.529720  3.026870  0.710888
553  3.385960  0.726641  0.463757 -0.391836
559  0.095660  0.470699 -3.004744  0.475521

In [150]:
data[np.abs(data)>3] = np.sign(data)*3

In [151]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.003071    -0.016973    -0.028031     0.011182
std       0.982837     0.996347     0.981120     1.005981
min      -2.729081    -2.946380    -3.000000    -2.822673
25%      -0.662756    -0.701593    -0.701784    -0.676590
50%      -0.009459    -0.046370    -0.034150     0.061440
75%       0.632105     0.673459     0.648194     0.714151
max       3.000000     2.985882     3.000000     2.873912

In [153]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [154]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [155]:
sampler = np.random.permutation(5)

In [157]:
sampler

array([4, 0, 2, 3, 1])

In [158]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [168]:
df.sample(3)

0  1   2   3
1  4  5   6   7
2  8  9  10  11
0  0  1   2   3

In [169]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'data1':range(6)})

In [170]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [171]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [172]:
dummies = pd.get_dummies(df['key'],prefix = 'key')

In [173]:
df_with_dummy = df[['data1']].join(dummies)

In [174]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [175]:
mnames = ['movie_id','title','genres']

In [176]:
movies = pd.read_table('F:/利用Python进行数据分析数据集/datasets/movielens/movies.dat',sep = '::',header = None,names = mnames)

G:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [177]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [178]:
all_genres = []

In [179]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [180]:
genres = pd.unique(all_genres) #去重并升序排列

In [181]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [182]:
zero_matrix = np.zeros((len(movies),len(genres)))

In [183]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [184]:
dummies = pd.DataFrame(zero_matrix,columns = genres)

In [185]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [186]:
gen = movies.genres[0]

In [187]:
gen

"Animation|Children's|Comedy"

In [188]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [189]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [191]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1

In [192]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [193]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [194]:
np.random.seed(12345)

In [195]:
values = np.random.rand(10)

In [196]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [197]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [198]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0