In [4]:
import numpy as np
import pandas as pd

In [5]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index = ['d','b','a','c'])

In [6]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [9]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [10]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [11]:
obj3 = pd.Series(['blue','purple','yellow'],index = [0,2,4])

In [12]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [13]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [14]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['a','c','d'],columns = ['Ohio','Texas','California'])

In [15]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [16]:
frame2 = frame.reindex(['a','b','c','d'])

In [17]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [18]:
states = ['Texas','Utah','California']

In [19]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [23]:
df = frame.loc[['a'],states]

In [24]:
df

Texas  Utah  California
a      1   NaN           2

In [25]:
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])

In [26]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [29]:
new_obj = obj.drop('c')

In [30]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [31]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [34]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index = ['Ohio','Colorado','Utah','New York'],columns = ['one','two','three','four'])

In [35]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
data.drop(['Ohio','Utah'])

one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [39]:
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [40]:
data.drop(['one','four'],axis = 1)

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [41]:
obj.drop('c',inplace = True)

In [42]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [43]:
obj = pd.Series(np.arange(4),index = ['a','b','c','d'])

In [44]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [46]:
obj['a']

0

In [51]:
obj[:-3]

a    0
dtype: int32

In [50]:
obj[-2:]

c    2
d    3
dtype: int32

In [52]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [53]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [60]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [61]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [62]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [63]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [64]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [67]:
data[data<5] = 0

In [68]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [70]:
data.loc['Colorado',['three','two']]

three    6
two      5
Name: Colorado, dtype: int32

In [72]:
data.iloc[1,[2,1]]

three    6
two      5
Name: Colorado, dtype: int32

In [73]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [74]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [76]:
data.loc['Utah':,'two']

Utah         9
New York    13
Name: two, dtype: int32

In [87]:
data.iloc[:,:3][data.three==10]

one  two  three
Utah    8    9     10

In [88]:
ser = pd.Series(np.arange(3.))

In [89]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [91]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [92]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [98]:
ser2[-1]

2.0

In [101]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [102]:
ser.iloc[:1]

0    0.0
dtype: float64

In [107]:
ser[:1]

0    0.0
dtype: float64

In [108]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index = ['a','c','d','e'])

In [109]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index = ['a','c','e','f','g'])

In [110]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [111]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [112]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [114]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns = list('bcd'),index = ['Ohio','Texas','Colorado'])

In [115]:
df2 = pd.DataFrame(np.arange(12).reshape((4,3)),columns = list('bde'),index = ['Utah','Ohio','Texas','Colorado'])

In [116]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [117]:
df2

b   d   e
Utah      0   1   2
Ohio      3   4   5
Texas     6   7   8
Colorado  9  10  11

In [118]:
df1+df2

b   c     d   e
Colorado  15.0 NaN  18.0 NaN
Ohio       3.0 NaN   6.0 NaN
Texas      9.0 NaN  12.0 NaN
Utah       NaN NaN   NaN NaN

In [121]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns = list('abcd'))

In [122]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [124]:
df2 = pd.DataFrame(np.arange(20).reshape((4,5)),columns = list('abcde'))

In [125]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [126]:
df2.loc[1,'b'] = np.nan

In [127]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [128]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [129]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [130]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [131]:
df1.div(1)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [132]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [133]:
arr = np.arange(12).reshape((3,4))

In [134]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
arr[0]

array([0, 1, 2, 3])

In [136]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [137]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),columns = list('bcd'),index = ['Utah','Ohio','Texas','Oregon'])

In [138]:
frame

b   c   d
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [140]:
series = frame.iloc[0]

In [141]:
series

b    0
c    1
d    2
Name: Utah, dtype: int32

In [142]:
frame-series

b  c  d
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [143]:
series2 = pd.Series(range(3),index = ['b','e','f'])

In [144]:
frame+series2

b   c   d   e   f
Utah    0.0 NaN NaN NaN NaN
Ohio    3.0 NaN NaN NaN NaN
Texas   6.0 NaN NaN NaN NaN
Oregon  9.0 NaN NaN NaN NaN

In [149]:
series3 = frame['d']

In [147]:
series3

Utah       2
Ohio       5
Texas      8
Oregon    11
Name: d, dtype: int32

In [154]:
frame.sub(series3,axis=0)

b  c  d
Utah   -2 -1  0
Ohio   -2 -1  0
Texas  -2 -1  0
Oregon -2 -1  0

In [155]:
frame = pd.DataFrame(np.random.randn(4,3),columns = list('bde'),index = ['Utah','Ohio','Texas','Oregon'])

In [156]:
frame

b         d         e
Utah    1.872197  1.923903 -0.594564
Ohio    0.943390  0.019081  0.460075
Texas   0.684123  0.602909 -0.543199
Oregon -0.839271  0.838832 -0.422447

In [157]:
frame.abs()

b         d         e
Utah    1.872197  1.923903  0.594564
Ohio    0.943390  0.019081  0.460075
Texas   0.684123  0.602909  0.543199
Oregon  0.839271  0.838832  0.422447

In [158]:
np.abs(frame)

b         d         e
Utah    1.872197  1.923903  0.594564
Ohio    0.943390  0.019081  0.460075
Texas   0.684123  0.602909  0.543199
Oregon  0.839271  0.838832  0.422447

In [162]:
f = lambda x: x.max()-x.min()

In [163]:
frame.apply(f)

b    2.711468
d    1.904822
e    1.054639
dtype: float64

In [165]:
frame.apply(f,axis=1)

Utah      2.518466
Ohio      0.924309
Texas     1.227322
Oregon    1.678103
dtype: float64

In [167]:
def f(x):
    return pd.Series([x.min(),x.max()],index = ['min','max'])


In [168]:
frame.apply(f)

b         d         e
min -0.839271  0.019081 -0.594564
max  1.872197  1.923903  0.460075

In [176]:
format1 = lambda x : '%.2f' % x

In [177]:
frame.applymap(format1)

b     d      e
Utah     1.87  1.92  -0.59
Ohio     0.94  0.02   0.46
Texas    0.68  0.60  -0.54
Oregon  -0.84  0.84  -0.42

In [178]:
frame['e'].map(format1)

Utah      -0.59
Ohio       0.46
Texas     -0.54
Oregon    -0.42
Name: e, dtype: object

In [187]:
obj = pd.Series(range(4),index = ['d','a','b','c'])

In [188]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [190]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [192]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index = ['three','one'],columns = list('dabc'))

In [193]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [196]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [198]:
frame.sort_index(axis=1,ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [199]:
obj = pd.Series([4,7,-3,2])

In [200]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [201]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [202]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [203]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [205]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [206]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [207]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [208]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [211]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [213]:
obj.rank(method='first',ascending = False)

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [214]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [223]:
frame = frame.sort_index(axis=1)

In [224]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [231]:
frame.rank(axis = 0,ascending=False,method = 'first')

a    b    c
0  3.0  2.0  3.0
1  1.0  1.0  2.0
2  4.0  4.0  1.0
3  2.0  3.0  4.0

In [232]:
obj = pd.Series(range(5),index = ['a','a','b','b','c'])

In [233]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [234]:
obj.index.is_unique

False

In [235]:
obj['a']

a    0
a    1
dtype: int64

In [236]:
df = pd.DataFrame(np.random.randn(4,3),index = ['a','a','b','b'])

In [237]:
df

0         1         2
a -1.344107 -0.278550  1.158961
a  0.346390  0.339178  1.372568
b  0.343280 -1.170815 -0.345425
b -1.218749  0.826457 -0.246722

In [238]:
df.loc['b']

0         1         2
b  0.343280 -1.170815 -0.345425
b -1.218749  0.826457 -0.246722